### ISSUE TITLE
[Suggestion] Custom title / window class for Kunst's sxiv window

### ISSUE THREAD

**Issue by anonaii** [sdushantha/kunst#2]
I'd like to use Kunst with i3's scratchpad feature to open when I show ncmpcpp, but Kunst uses sxiv's default class name for the window it opens, making it impossible to do so without making all sxiv windows follow the same rule as Kunst's window.

**Comment by sdushantha** [comment]
That is a great idea! But, I have no idea how to set a custom title for sxiv or a custom window class.
I know that there is a ```-N``` which lets you *Set the resource name of sxiv's X window to NAME.* I am not really sure if that fixes it because when I tried it, i3 did not detect anything.

Do you maybe know how to do this?

**Comment by mateossh** [comment]
You can use tool called `xdotool` to change window's title / class etc.

**Comment by sdushantha** [comment]
@mateossh 
Do you know how to do it? I have never used `xdotool` before.

**Comment by mateossh** [comment]
Made pull request #6. As @sdushantha mentioned earlier, I just add `-N` flag to sxiv (no more dependencies). 

Now if you want to refer to Kunst's sxiv window in i3 config - rule is as follows
`for_window [instance="KunstArt"] .....`
